services:
  web:
    container_name: pd2-web
    build: ./
    ports:
      - 3000:3000

  mysql:
    container_name: pd2-mysql
    image: mysql:latest
    volumes:
      - './mysql:/var/lib/mysql'
    ports:
      - 3306:3306
    environment:
      - TZ=Europe/Riga
      - MYSQL_DATABASE=pd2
      - MYSQL_USER=pd2admin
      - MYSQL_PASSWORD=pd2pass
      - MYSQL_ROOT_PASSWORD=root

  database-admin:
    container_name: pd2-adminer
    image: adminer:latest
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Riga
      - ADMINER_DEFAULT_SERVER=pd2-mysql
